# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09b0bf31970b66b1440caa7cd9c404406b25f2db2a79dccbcf435546c0a68a415f93a8a86579970e46250d3552b20ab3a5a09889a0e6f6d774a086e4da04bedc

test:
  secret_key_base: c149e5fbbca68a030f59cd553ba8700e7b8ab5553093477aa0a27d0942baaa709ad2ea19e80a9a4b68916080f2e02377a33906e233199ce4a1d0899b211e8cde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
